#https://golangci-lint.run/usage/linters/
version: "2"
linters:
  default: none
  enable:
    - ireturn
    - err113
    - revive
    - gosec
    - errcheck
    - nilnil
    - nilerr
    - staticcheck
