env:
  - CGO_ENABLED=0
  - REPO_OWNER=solarwinds
  - REPO_NAME=swo-cli

builds:
  - main: ./cmd/swo/main.go
    id: linux
    binary: swo
    ldflags:
      - "-s -w -X 'main.version=v{{ .Version }}'"
    targets:
      - darwin_amd64
      - darwin_arm64
      - linux_amd64
      - linux_arm64
  - main: ./cmd/swo/main.go
    id: win
    binary: swo
    ldflags:
      - "-s -w -X 'main.version=v{{ .Version }}'"
    targets:
      - windows_amd64
    hooks:
      post:
        - env:
            - SP_SIGNING_POLICY=Release
            - SP_ARTIFACT_CONFIGURATION=exe
          cmd: pwsh -c "Submit-SigningRequest -ApiToken "$env:SP_CI_USER_TOKEN" -OrganizationId "$env:SP_ORGANIZATION_ID" -ProjectSlug "$env:SP_PROJECT" -SigningPolicySlug "$env:SP_SIGNING_POLICY" -ArtifactConfigurationSlug "$env:SP_ARTIFACT_CONFIGURATION" -InputArtifactPath '{{ .Path }}' -OutputArtifactPath '{{ .Path }}' -Force -WaitForCompletion"
          output: true

archives:
  - builds:
      - win
      - linux
      - mac
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
    format: zip

universal_binaries:
  - id: mac
    ids:
      - "linux"
    replace: true
    name_template: "swo"

notarize:
  macos:
    - enabled: '{{ isEnvSet "SWO_MAC_P12_CERT" }}'
      ids:
        - mac
      sign:
        certificate: "{{.Env.SWO_MAC_P12_CERT}}"
        password: "{{.Env.SWO_P12_PASSWORD}}"

      notarize:
        issuer_id: "{{.Env.SWO_ISSUER_ID}}"
        key_id: "{{.Env.SWO_KEY_ID}}"
        key: "{{.Env.SWO_MAC_P8_FILE}}"
        wait: true
        timeout: 20m

checksum:
  name_template: '{{ .ProjectName }}_checksums.txt'
