env:
  - CGO_ENABLED=0
  - REPO_OWNER=solarwinds
  - REPO_NAME=swo-cli
builds:
  - main: ./cmd/swo/main.go
    binary: swo
    ldflags:
      - "-s -w -X 'main.version=v{{ .Version }}'"
    targets:
      - darwin_amd64
      - darwin_arm64
      - linux_amd64
      - linux_arm64
      - windows_amd64
archives:
  - id: zip
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
    format: zip

universal_binaries:
  - replace: true
    name_template: "swo"

checksum:
  name_template: 'checksums.txt'
